Repository wneessen/go-mail, pull requests merged in 2022-10, with the labels that each got.

#57 Add GetGenHeader to Msg
  msg.go
  msg_test.go
Labels: hacktoberfest, hacktoberfest-accepted

#61 Expose Msg bodypart fields
  msg.go
  part.go
  part_test.go
Labels: enhancement, hacktoberfest

#63 Expose Msg attachments fields
  msg.go
  msg_test.go
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#66 Introduce golangci-lint
  .github/workflows/golangci-lint.yml
  .gitignore
  .golangci.toml
  auth/auth_test.go
  client.go
  client_test.go
  doc_test.go
  encoding.go
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#67 Fix codecov Go version setup
  .github/workflows/codecov.yml
  .github/workflows/sonarqube.yml
Labels: hacktoberfest, hacktoberfest-accepted

#70 Introducing MiddlewareType and WriteToSkipMiddleware
  msg.go
  msg_test.go
Labels: hacktoberfest, hacktoberfest-accepted

#75 Fixed SetMessageID message ID generation
  msg.go
  msg_test.go
  random.go
  random_test.go
Labels: hacktoberfest, hacktoberfest-accepted

#77 Add SetHeaderPreformatted() method
  msg.go
  msg_test.go
  msgwriter.go
Labels: hacktoberfest, hacktoberfest-accepted
